const TESTING_CONSTANTS = {
  TESTING_USER_USERNAME: process.env.TEST_USER_USERNAME ?? "test_user1",
  TESTING_USER_PASSWORD: process.env.TEST_USER_PASSWORD ?? "test_user1",
  TESTING_WEB_SERVER_PORT: 12345
};

export { TESTING_CONSTANTS };
